Upgrade to rebar3 and configure some style rules
SyncFree/antidote_crdt pull request #3
Opened 2016-11-02 22:22 UTC by vitorenesduarte

2016-11-02 23:05 UTC, peterzeller requested changes

2016-11-02 23:05 UTC, peterzeller commented on src/antidote_crdt_bcounter.erl
> +-export([local_permissions/2,
maybe move changes of the public interface to a different pull request

2016-11-02 23:05 UTC, peterzeller commented on src/antidote_crdt_mvreg.erl
> +insert_sort(A, []) -> [A];
The name was to be short for "insert into sorted list", so I would keep the old name "insert sorted"

2016-11-02 23:05 UTC, peterzeller commented on src/antidote_crdt_orset.erl
> +            [];
I think it's nicer to use `orddict:new` here and be explicit about the used data structure

2016-11-02 23:05 UTC, peterzeller commented on src/antidote_crdt_set_rw.erl
> +elems_with_removed_tombstones([E|ElemsRest], [{K, Ts}|DictRest], ResetTokens) when E == K ->
I think the old version with the `if` is more readable. Here the important condition is lost among the pattern matches...

2016-11-03 08:30 UTC, vitorenesduarte commented
Hi @peterzeller.
Following your suggestions, the last commit 3e9f6218dfbaa23359bba5aca0dd873300b0f202
- reverts the changes related to the style `no_if_expression`
- renames `local_permissions` to `localPermissions` to keep the API
- renames `insert_sort` to `insert_sorted` (this was a bad find and replace)

2016-11-03 08:32 UTC, vitorenesduarte commented on src/antidote_crdt_orset.erl
> +            [];
I changed it because I think we are returning a list of tokens and not a dictionary.

2016-11-03 09:11 UTC, peterzeller commented on src/antidote_crdt_orset.erl
> +            [];
You are right, I was confused because the case above had a different return type. Maybe we can also change the signature to make this clear:

```
-spec value({fragment, member()}, orset()) -> orset();
           ({tokens, member()}, orset()) -> [Token::any()].
```

2016-11-03 10:08 UTC, vitorenesduarte commented on src/antidote_crdt_orset.erl
> +            [];
What does `Token::any()` mean?
I just checked http://erlang.org/doc/man/crypto.html#strong_rand_bytes-1
Does it make sense to use `binary()` here?

2016-11-03 10:33 UTC, peterzeller commented on src/antidote_crdt_orset.erl
> +            [];
Yes, that would be more precise. `Token::any()` means that any value can be in the list and `Token::` is just a name for documenting what the value represents.

If we are already fixing the types: The types for downstream operations is also wrong. 

```
% Changed types:
-opaque orset() :: orddict:orddict(member(), [token()]).

-type orset_downstream_op() ::
      {add, member_with_tokens()}
    | {remove, member_with_tokens()}
    | {add_all, [member_with_tokens()]}
    | {remove_all, [member_with_tokens()]}.

-type member() :: term().
-type token() :: binary().
-type member_with_tokens() :: {member(), [token()]}.

% Spec for value
-spec value({fragment, member()}, orset()) -> orset();
           ({tokens, member()}, orset()) -> [token()].

% spec fo downstream:
 -spec downstream(orset_op(), orset()) -> {ok, orset_downstream_op()}.

% spec for update:
-spec update(orset_downstream_op(), orset()) -> {ok, orset()}.
```

Or we can fix this later ...

2016-11-03 11:03 UTC, vitorenesduarte commented on src/antidote_crdt_orset.erl
> +            [];
I changed to

```
-spec value({fragment, member()}, orset()) -> orset();
           ({tokens, member()}, orset()) -> [binary()].
```

We have an optimization for the ORSet and I can fix these types in that PR.
Is this okay?

2016-11-03 11:48 UTC, peterzeller approved these changes

2016-11-03 16:03 UTC, CBaquero commented
Can I click the merge button for this pull request? Since changes have been approved.

Next we will do individual pull requests for each datatype that can be revised.

2016-11-03 16:04 UTC, merged